### ISSUE TITLE
gcp: Community Parity

### ISSUE THREAD

**Issue by sergenyalcin** [crossplane-contrib/provider-upjet-gcp#16]
List:

- [ ] [google_dns_record_set](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dns_record_set) https://github.com/upbound/official-providers/issues/445
- [ ] [google_kms_crypto_key](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/kms_crypto_key) https://github.com/upbound/official-providers/issues/446
- [ ] [google_kms_key_ring](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/kms_key_ring) https://github.com/upbound/official-providers/issues/446
- [x] [google_pubsub_topic](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/pubsub_topic) https://github.com/upbound/official-providers/issues/394
- [x] [google_pubsub_subscription](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/pubsub_subscription)
- [ ] [google_container_registry](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_registry) https://github.com/upbound/official-providers/issues/447
- [ ] [google_service_networking_connection](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/service_networking_connection) https://github.com/upbound/official-providers/issues/448
- [ ] [google_project_iam_member](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/project_iam_member) https://github.com/upbound/provider-gcp/issues/20
- [ ] [google_service_account_iam_member](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/service_account_iam_member) https://github.com/upbound/provider-gcp/issues/20
- [ ] [google_service_account_iam_policy](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/service_account_iam_policy) https://github.com/upbound/provider-gcp/issues/20
- [ ] [google_compute_network_peering](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_network_peering) https://github.com/upbound/official-providers/issues/276
- [ ] [google_secret_manager_secret](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/secret_manager_secret) https://github.com/upbound/official-providers/issues/284
- [ ] [google_secret_manager_secret_version](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/secret_manager_secret_version) https://github.com/upbound/official-providers/issues/284

Milestone: https://github.com/upbound/official-providers/milestone/7
